version: '3.9'

services:

  # 1. EXPRESS.JS API GATEWAY (Entry Point)
  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8003:3000" # Maps local port 8003 to Express internal port 3000
    networks:
      - microservice-network
    depends_on:
      - frontend
      - payment-nginx

  # 2. FRONT END (Static HTML/Tailwind Server)
  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    networks:
      - microservice-network

  # 3a. PAYMENT SERVICE - PHP APP
  payment-service-app:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./payment-service:/var/www
    networks:
      - microservice-network
    depends_on:
      - payment-db

  # 3b. PAYMENT SERVICE - WEB SERVER
  payment-nginx:
    image: nginx:latest
    container_name: payment-nginx
    restart: unless-stopped
    volumes:
      - ./payment-service:/var/www
      - ./payment-service/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservice-network
    depends_on:
      - payment-service-app

  # 4. DATABASE
  payment-db:
    image: mysql:8.0
    container_name: payment-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: payment_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge