services:

  payment-service-app:
    build:
      context: ./payment-service
      dockerfile: Dockerfile

    container_name: payment-service-app

    restart: unless-stopped

    working_dir: /var/www

    volumes:
      - ./payment-service:/var/www

    networks:
      - microservice-network

    depends_on:
      - payment-db

  payment-nginx:
    image: nginx:latest

    container_name: payment-nginx

    restart: unless-stopped

    ports:
      - "8003:80"

    volumes:
      - ./payment-service:/var/www
      - ./payment-service/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - microservice-network

    depends_on:
      - payment-service-app

  payment-db:
    image: mysql:8.0

    container_name: payment-db

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: payment_service
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"

    networks:
      - microservice-network

  booking-service-app:
    build:
      context: ./booking-service
      dockerfile: Dockerfile

    container_name: booking-service-app

    restart: unless-stopped

    working_dir: /var/www

    volumes:
      - ./booking-service:/var/www

    networks:
      - microservice-network

    depends_on:
      - booking-db

  booking-nginx:
    image: nginx:latest

    container_name: booking-nginx

    restart: unless-stopped

    ports:
      - "8002:80"

    volumes:
      - ./booking-service:/var/www
      - ./booking-service/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    networks:
      - microservice-network

    depends_on:
      - booking-service-app

  booking-db:
    image: mysql:8.0

    container_name: booking-db

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: booking_service
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3308:3306"

    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge